## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [167]:
import numpy as np
print(np.linspace(-1.3, 2.5, 65))

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [168]:
n = int(input())
print(np.array([1, 2, 3] * n))

3
[1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [169]:
print(np.linspace(1, 19, 10, dtype=np.int32))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [170]:
c = np.zeros((10, 10), dtype=np.int32)
c[0, :] = 1
c[9, :] = 1
c[:, 0] = 1
c[:, 9] = 1
print(c)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [171]:
d = np.zeros((8, 8), dtype=np.int32)
d[0:8:2, 0:8:2] = 1
d[1:8:2, 1:8:2] = 1
print(d)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [172]:
n = int(input())
def matrix(n):
    e = np.indices((n, n), dtype=np.int32)
    e.shape
    return e[0] + e[1]
print(matrix(n))

3
[[0 1 2]
 [1 2 3]
 [2 3 4]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [173]:
n = int(input())
f = np.random.randint(1, 11, n)
g = np.random.randint(1, 11, (n, n))
vv = np.dot(f, f)
mv = np.dot(g, f)
mm = np.dot(g, g)
print('vector:', f, '\n\nmatrix:\n\n', g, \
      '\n\nvector * vector:', vv, '\n\nmatrix * vector:', mv, '\n\nmatrix * matrix:\n\n', mm)

3
vector: [3 3 8] 

matrix:

 [[ 7  6  6]
 [ 9  2  8]
 [ 1 10  3]] 

vector * vector: 82 

matrix * vector: [87 97 57] 

matrix * matrix:

 [[109 114 108]
 [ 89 138  94]
 [100  56  95]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [174]:
h = np.cos(np.arange(0, 1, 0.05))
i = np.sin(np.arange(0, 1, 0.05))
j = np.vstack([h, i])
print(j)

[[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309]
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155 ]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [175]:
a, b = -1, 3
A = (b - a) * np.random.rand(3, 5) + a
print(A)

[[ 2.5983306   1.09409135  0.84512521  1.21698934  0.37311028]
 [-0.26216337  0.92643629  0.14811282 -0.60969618  0.81401157]
 [ 0.9054992   1.65553894  0.62083002  1.17001282  1.34232488]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [176]:
print('sum:', np.sum(A), '\nsumstr:', np.sum(A, axis = 1), '\nsumcol:', np.sum(A, axis = 0), \
'\nmeanstr:', np.mean(A, axis = 1), '\nvarstr:', np.var(A, axis = 1), '\nstdstr:', np.std(A, axis =1))

sum: 12.838553783163485 
sumstr: [6.12764678 1.01670114 5.69420587] 
sumcol: [3.24166644 3.67606658 1.61406805 1.77730598 2.52944672] 
meanstr: [1.22552936 0.20334023 1.13884117] 
varstr: [0.55465155 0.35531185 0.12642758] 
stdstr: [0.74474932 0.59608041 0.35556656]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [177]:
k = np.repeat(np.mean(A, axis = 1), 5).reshape(3,5)
l = np.repeat(np.std(A, axis = 1), 5).reshape(3,5)
print('Answer:\n\n', np.divide(np.subtract(A, k), l))

Answer:

 [[ 1.84330648 -0.17648624 -0.51078146 -0.01146697 -1.14457181]
 [-0.78094094  1.21308477 -0.09265094 -1.36397102  1.02447813]
 [-0.65625398  1.45316749 -1.45686126  0.08766756  0.5722802 ]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [178]:
print('sort:\n\n', A[A[:, 2].argsort()])

sort:

 [[-0.26216337  0.92643629  0.14811282 -0.60969618  0.81401157]
 [ 0.9054992   1.65553894  0.62083002  1.17001282  1.34232488]
 [ 2.5983306   1.09409135  0.84512521  1.21698934  0.37311028]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [179]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))
print('B =\n\n', B, '\n\nC =\n\n', C)
print('\nМатрица B и матрица С - симметричные. Размер матриц B и C - 5*5, 3*3 соответственно.')
print('\nСходство - симметричность, сумма диагональных элементов. Отличие - размер, значения элементов.')

B =

 [[7.63998037 4.09902258 2.71924603 4.38142632 1.97153394]
 [4.09902258 4.79612927 2.08966955 2.70365463 3.38461769]
 [2.71924603 2.08966955 1.12160395 1.66458364 1.26924603]
 [4.38142632 2.70365463 1.66458364 3.22172248 1.5283088 ]
 [1.97153394 3.38461769 1.26924603 1.5283088  2.60366219]] 

C =

 [[10.28286876  0.01931505  6.61350457]
 [ 0.01931505  1.98329551  1.76763116]
 [ 6.61350457  1.76763116  7.11693399]]

Матрица B и матрица С - симметричные. Размер матриц B и C - 5*5, 3*3 соответственно.

Сходство - симметричность, сумма диагональных элементов. Отличие - размер, значения элементов.


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [180]:
print(np.trace(B), np.trace(C))

19.383098257095725 19.383098257095725


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [181]:
q, r = np.linalg.eig(B)
s, t = np.linalg.eig(C)
print('Нельзя найти детерминант матрицы А, т. к. она не квадратная.')
print('\nДетерминант матриц B, C =', np.linalg.det(B), ',', \
      np.linalg.det(C), 'соответственно')
print('\nРанг матриц A, B, C =', np.linalg.matrix_rank(A), ',', np.linalg.matrix_rank(B), ',', \
      np.linalg.matrix_rank(C), 'соответственно')
print('\nСобственные значения матрицы B =\n\n', q, '\n\nСобственные значения матрицы С =', s)
print('\nКоличество собственных значений совпадает с размерностью матрицы.')

Нельзя найти детерминант матрицы А, т. к. она не квадратная.

Детерминант матриц B, C = 0.0 , 26.716174680510278 соответственно

Ранг матриц A, B, C = 3 , 3 , 3 соответственно

Собственные значения матрицы B =

 [ 1.55916763e+01  3.26692594e+00  5.24495993e-01 -3.49206715e-18
  5.42577064e-16] 

Собственные значения матрицы С = [15.59167632  3.26692594  0.52449599]

Количество собственных значений совпадает с размерностью матрицы.


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [182]:
np.random.seed(1032201733)
print(np.random.randint(9))

2


Аналитическое решение интеграла №2$: \frac{e - \sqrt[4]{e}}{2} \approx 0.71712820$

Аналитическое решение интеграла №9$: \frac{\pi}{2^\frac{3}{2}} \approx 1.11072073$

In [183]:
import math
h2 = 0.00001
h9 = 0.0000001
m = int((2 - 3 / 4) / h9)
xx = np.arange(1, 2, h2)
x = np.append(xx, 2)
y = np.linspace(3 / 4, 2, m, endpoint=False)

def func2(x):
    return (math.e ** (1 / x ** 2) / x ** 3)

def func9(x):
    return 1 / np.sqrt(2 + 3 * x - 2 * x ** 2, where = x!=2)

rect2 = h2 * np.sum(func2(x))
trape2 = h2 / 2 * (func2(x[0]) + 2 * np.sum(func2(x[1:-1])) + func2(x[-1]))
simp2 = h2 / 3 * (func2(x[0]) + 2 * np.sum(func2(x[2:-1:2])) + 4 * np.sum(func2(x[1:-2:2])) + func2(x[-1]))

rect9 = h9 * np.sum(func9(y))
trape9 = h9 / 2 * (func9(y[0]) + 2 * np.sum(func9(y[1:-1])) + func9(y[-1]))
simp9 = h9 / 3 * (func9(y[0]) + 2 * np.sum(func9(y[2:-1:2])) + 4 * np.sum(func9(y[1:-2:2])) + func9(y[-1]))

print('Метод прямоугольников №2 =', rect2, '\nМетод трапеций №2 =', trape2, '\nПравило Симпсона №2 =', simp2)
print('\nМетод прямоугольников №9 =', rect9, '\nМетод трапеций №9 =', trape9, '\nПравило Симпсона №9 =', simp9)
print('\nВывод: С помощью численных методов можно посчитать интеграл с заданной точностью.')
print('       Чем меньше шаг интегрирования, тем точнее решение.')

Метод прямоугольников №2 = 0.7171425999179543 
Метод трапеций №2 = 0.7171282059929266 
Правило Симпсона №2 = 0.7171260658021932

Метод прямоугольников №9 = 1.1105142375079518 
Метод трапеций №9 = 1.1104434985441538 
Правило Симпсона №9 = 1.1104013030605193

Вывод: С помощью численных методов можно посчитать интеграл с заданной точностью.
       Чем меньше шаг интегрирования, тем точнее решение.
